{
	"version": 1651493560,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"assets/images/player-sheet0.png",
		"assets/images/tiledbackground.png",
		"assets/images/bullet-sheet0.png",
		"assets/images/enemy-sheet0.png",
		"assets/images/bullet2-sheet0.png",
		"assets/images/bullet3-sheet0.png",
		"assets/images/bullet4-sheet0.png",
		"assets/images/bullet5-sheet0.png",
		"assets/images/trap-sheet0.png",
		"assets/bullet-3.m4a",
		"assets/bullet-3.ogg",
		"assets/laser-shot.m4a",
		"assets/laser-shot.ogg",
		"assets/stage 2.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"stage 2.json"
	]
}